pkg/plugin: handle "AccessDeniedException" as user-induced
e.g.,

AccessDeniedException: The ciphertext refers to a customer master key that does not exist, does not exist in this
region, or you are not allowed to access.

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>